### PR TITLE
Release CLI: v0.4.0

### PR DESCRIPTION
**Pull request by utkarsh867**

### CODE REVIEW

**Comment by utkarsh867** [comment]
@98sean98 Let me know if you see any side effects of downgrading cryptography. Technically, I can copy over the resource block for v38.

Not sure what are the breaking changes in 36.

**Comment by 98sean98** [comment]
I've regenerated the file with my environment.

Python 3.7.16
`cryptography 39`

Quite confident that this is going to work.

**Comment by utkarsh867** [comment]
I believe that Python 3.7 will not support users on brew. It has been marked as deprecated. Will shift back to 3.9 with the same dependencies.

**Comment by utkarsh867** [comment]
I've installed and seems to work fine. Will pull this in if it looks good to you @98sean98 

Screenshot 2023-02-27 at 11 24 11 PM

**Review by 98sean98 — APPROVED** [review]

**Pull request merged**
